@startuml
'状态模式（State）
'当一个对象的内在状态改变时允许改变其行为，
'这个对象看起来像是改变了其类

class Contex{
    +void request()
}

abstract class State{
    + {abstract} handler()
}

class ConcreteStateA{
    + handler()
}

class ConcreteStateB{
    + handler()
}

class ConcreteStateC{
    + handler()
}

State <|-- ConcreteStateA : extends
State <|-- ConcreteStateB : extends
State <|-- ConcreteStateC : extends
Contex o-- State : Aggregation

@enduml